#!/bin/sh

ipcs -m | grep ^0x7 | awk '{ print $2; }' | xargs -r ipcrm shm

ipcs -s | grep ^0x0 | grep "\b660\b" | awk '{ print $2; }' | xargs -r ipcrm sem
ipcs -m | grep ^0x0 | grep "\b660\b" | awk '{ print $2; }' | xargs -r ipcrm shm
ipcs -q | grep ^0x0 | grep "\b660\b" | awk '{ print $2; }' | xargs -r ipcrm msg
