#!/bin/sh

if test -z "$3"; then
  echo "Usage:   $0 <enum> <prefix> <header>"
  echo "Example: $0 FooResult FOO foo_types.h"
  exit 1
fi

ENUM=$1
PREFIX=$2
HEADER=$3


cat << EOF
/*
 * Generated by mkresult.sh
 */

#include <direct/result.h>

static const char *${ENUM}__strings[] = {
     "${ENUM}",

EOF

(
    while read line; do
        (echo "$line" | egrep -q "^${PREFIX}__RESULT_BASE += +D_RESULT_TYPE_CODE_BASE") && break
    done

    while read line; do
        (echo "$line" | egrep -q "^ *} +${ENUM};") && break

        test -z "$line" || echo "$line" | perl -p -e "s/^\\s*(${PREFIX}_[\\w_]+)\\s*,?\\s+\\/\\*\\s*(.*[^ ])\\s*\\*\\//     [D_RESULT_INDEX(\\1)] = \\\"\\2\\\",/"
    done
) < ${HEADER}

cat << EOF
};                                         

DIRECT_RESULT_TYPE( ${ENUM}, ${PREFIX} );

EOF

