CROSS_COMPILE = arm-v4t-linux-gnueabi-
KERNEL_SOURCE = $(shell pwd)/../../../linux-davinci-2.6
KERNEL_BUILD  = $(KERNEL_SOURCE)

all:
	$(MAKE) -C kernel-module KERNEL_SOURCE=$(KERNEL_SOURCE) KERNEL_BUILD=$(KERNEL_BUILD)
